import logging
import asyncio
import httpx
from datetime import datetime
from config import DISCORD_WEBHOOK_URL

async def send_header(count: int):
    if not DISCORD_WEBHOOK_URL:
        logging.warning("Discord webhook URL not provided.")
        return
        
    date_str = datetime.utcnow().strftime("%Y-%m-%d")
    content = f"**Research Digest** | {date_str} | Found {count} new article(s)."
    
    await _send_to_discord({"content": content})

async def send_article(article, summary: str):
    if not DISCORD_WEBHOOK_URL:
        return
        
    title = article.get("title", "No Title")
    journal = article.get("journal", "Unknown Journal")
    authors = article.get("authors", "Unknown Authors")
    pub_date = article.get("pub_date", "")
    article_type = article.get("article_type", "Unknown Type")
    doi = article.get("doi", "")
    pmid = article.get("pmid", "")
    
    url = f"https://doi.org/{doi}" if doi else f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/"
    
    journal_details = f"**Type:** {article_type}\n**Journal:** {journal}\n**Date:** {pub_date}\n**Authors:** {authors}\n\n"
    
    embed = {
        "title": title,
        "url": url,
        "color": 3447003, # Blue
    }
    
    # Discord description limit is 4096. Embed total limit is 6000.
    # Put summary in description because it's long and formatted.
    full_description = journal_details + summary
    embed["description"] = full_description[:4096]
    
    await _send_to_discord({"embeds": [embed]})

async def _send_to_discord(payload, retry_count=0):
    async with httpx.AsyncClient() as client:
        try:
            resp = await client.post(DISCORD_WEBHOOK_URL, json=payload, timeout=10.0)
            
            if resp.status_code == 429:
                data = resp.json()
                # `retry_after` is dynamically generated by Discord
                retry_after = data.get("retry_after", 5) 
                logging.warning(f"Discord rate limit hit. Waiting for {retry_after} seconds.")
                await asyncio.sleep(retry_after)
                if retry_count < 3:
                    await _send_to_discord(payload, retry_count + 1)
                else:
                    logging.error("Failed to send discord message after 3 429 retries")
            else:
                resp.raise_for_status()
                
        except Exception as e:
            logging.error(f"Error sending to Discord: {e}")
